spring.application.name=easySettle

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# So you can see what tables Hibernate creates
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sujal
spring.datasource.password=sujal123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# open-in-view fix from before
spring.jpa.open-in-view=false