spring.application.name=easySettle

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/easysettle
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable open-in-view
spring.jpa.open-in-view=false